server:
  port: 8083
  tomcat:
    max-threads: 100

spring:
  application:
    name: rating-data-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
config: some value