spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vskrahul/spring-boot-microservices.git
          searchPaths: microservices-config/{application}
      bootstrap: true
  application:
    name: config-server

server:
  port: 8888